version: "3.8"

x-custom:
  &shaas-base
  build:
    context: ..
  volumes:
    - ./fixtures:/ftest/fixtures:ro

services:
  shaas.default:
    << : *shaas-base
    ports:
      - "7575:7575"
  shaas.auth:
    << : *shaas-base
    ports:
      - "5001:7575"
    environment:
      - BASIC_AUTH=user:pass
  shaas.readonly:
    << : *shaas-base
    ports:
      - "5002:7575"
    environment:
      - READ_ONLY=1
