name: Build Go Binary

#on:
#  push:
#    branches: [master]
#  pull_request:
#    branches: [master]

jobs:
  build:
    name: Build for ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [amd64, arm64] # Add arm64 if needed
        exclude:
          - os: windows-latest
            arch: arm64 # Windows doesn't support arm64 in GitHub Actions

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.16'
      - run: go mod tidy

      - uses: actions/setup-go@v4
        with:
          go-version: '1.16'
      - run: go mod vendor

      - name: Build
        run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -v -o my-binary-${{ matrix.os }}-${{ matrix.arch }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: shaas${{ matrix.os }}-${{ matrix.arch }}
          path: shaas-${{ matrix.os }}-${{ matrix.arch }}